// Re-export utility modules for consumers
export * from './toolSchema.js';
export * from './toolArgs.js';
export * from './toolResults.js';

export const BLOOMREACH_STATUS_TOOL = 'bloomreach.session.status';
export const BLOOMREACH_DASHBOARDS_LIST_TOOL = 'bloomreach.dashboards.list';
export const BLOOMREACH_DASHBOARDS_PREPARE_CREATE_TOOL = 'bloomreach.dashboards.prepare_create';
export const BLOOMREACH_DASHBOARDS_PREPARE_SET_HOME_TOOL = 'bloomreach.dashboards.prepare_set_home';
export const BLOOMREACH_DASHBOARDS_PREPARE_DELETE_TOOL = 'bloomreach.dashboards.prepare_delete';
export const BLOOMREACH_PERFORMANCE_PROJECT_TOOL = 'bloomreach.performance.project';
export const BLOOMREACH_PERFORMANCE_CHANNEL_TOOL = 'bloomreach.performance.channel';
export const BLOOMREACH_PERFORMANCE_USAGE_TOOL = 'bloomreach.performance.usage';
export const BLOOMREACH_PERFORMANCE_OVERVIEW_TOOL = 'bloomreach.performance.overview';
export const BLOOMREACH_PERFORMANCE_HEALTH_TOOL = 'bloomreach.performance.health';
export const BLOOMREACH_SCENARIOS_LIST_TOOL = 'bloomreach.scenarios.list';
export const BLOOMREACH_SCENARIOS_VIEW_TOOL = 'bloomreach.scenarios.view';
export const BLOOMREACH_SCENARIOS_PREPARE_CREATE_TOOL = 'bloomreach.scenarios.prepare_create';
export const BLOOMREACH_SCENARIOS_PREPARE_START_TOOL = 'bloomreach.scenarios.prepare_start';
export const BLOOMREACH_SCENARIOS_PREPARE_STOP_TOOL = 'bloomreach.scenarios.prepare_stop';
export const BLOOMREACH_SCENARIOS_PREPARE_CLONE_TOOL = 'bloomreach.scenarios.prepare_clone';
export const BLOOMREACH_SCENARIOS_PREPARE_ARCHIVE_TOOL = 'bloomreach.scenarios.prepare_archive';
export const BLOOMREACH_EMAIL_CAMPAIGNS_LIST_TOOL = 'bloomreach.email_campaigns.list';
export const BLOOMREACH_EMAIL_CAMPAIGNS_VIEW_RESULTS_TOOL =
  'bloomreach.email_campaigns.view_results';
export const BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_CREATE_TOOL =
  'bloomreach.email_campaigns.prepare_create';
export const BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_SEND_TOOL =
  'bloomreach.email_campaigns.prepare_send';
export const BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_CLONE_TOOL =
  'bloomreach.email_campaigns.prepare_clone';
export const BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_ARCHIVE_TOOL =
  'bloomreach.email_campaigns.prepare_archive';
export const BLOOMREACH_SURVEYS_LIST_TOOL = 'bloomreach.surveys.list';
export const BLOOMREACH_SURVEYS_VIEW_RESULTS_TOOL = 'bloomreach.surveys.view_results';
export const BLOOMREACH_SURVEYS_PREPARE_CREATE_TOOL = 'bloomreach.surveys.prepare_create';
export const BLOOMREACH_SURVEYS_PREPARE_START_TOOL = 'bloomreach.surveys.prepare_start';
export const BLOOMREACH_SURVEYS_PREPARE_STOP_TOOL = 'bloomreach.surveys.prepare_stop';
export const BLOOMREACH_SURVEYS_PREPARE_ARCHIVE_TOOL = 'bloomreach.surveys.prepare_archive';
export const BLOOMREACH_CAMPAIGNS_CALENDAR_VIEW_TOOL = 'bloomreach.campaigns_calendar.view';
export const BLOOMREACH_CAMPAIGNS_CALENDAR_FILTER_TOOL = 'bloomreach.campaigns_calendar.filter';
export const BLOOMREACH_CAMPAIGNS_CALENDAR_PREPARE_EXPORT_TOOL =
  'bloomreach.campaigns_calendar.prepare_export';
export const BLOOMREACH_TRENDS_LIST_TOOL = 'bloomreach.trends.list';
export const BLOOMREACH_TRENDS_VIEW_RESULTS_TOOL = 'bloomreach.trends.view_results';
export const BLOOMREACH_TRENDS_PREPARE_CREATE_TOOL = 'bloomreach.trends.prepare_create';
export const BLOOMREACH_TRENDS_PREPARE_CLONE_TOOL = 'bloomreach.trends.prepare_clone';
export const BLOOMREACH_TRENDS_PREPARE_ARCHIVE_TOOL = 'bloomreach.trends.prepare_archive';
export const BLOOMREACH_FUNNELS_LIST_TOOL = 'bloomreach.funnels.list';
export const BLOOMREACH_FUNNELS_VIEW_RESULTS_TOOL = 'bloomreach.funnels.view_results';
export const BLOOMREACH_FUNNELS_PREPARE_CREATE_TOOL = 'bloomreach.funnels.prepare_create';
export const BLOOMREACH_FUNNELS_PREPARE_CLONE_TOOL = 'bloomreach.funnels.prepare_clone';
export const BLOOMREACH_FUNNELS_PREPARE_ARCHIVE_TOOL = 'bloomreach.funnels.prepare_archive';
export const BLOOMREACH_RETENTIONS_LIST_TOOL = 'bloomreach.retentions.list';
export const BLOOMREACH_RETENTIONS_VIEW_RESULTS_TOOL = 'bloomreach.retentions.view_results';
export const BLOOMREACH_RETENTIONS_PREPARE_CREATE_TOOL = 'bloomreach.retentions.prepare_create';
export const BLOOMREACH_RETENTIONS_PREPARE_CLONE_TOOL = 'bloomreach.retentions.prepare_clone';
export const BLOOMREACH_RETENTIONS_PREPARE_ARCHIVE_TOOL = 'bloomreach.retentions.prepare_archive';
export const BLOOMREACH_FLOWS_LIST_TOOL = 'bloomreach.flows.list';
export const BLOOMREACH_FLOWS_VIEW_RESULTS_TOOL = 'bloomreach.flows.view_results';
export const BLOOMREACH_FLOWS_PREPARE_CREATE_TOOL = 'bloomreach.flows.prepare_create';
export const BLOOMREACH_FLOWS_PREPARE_CLONE_TOOL = 'bloomreach.flows.prepare_clone';
export const BLOOMREACH_FLOWS_PREPARE_ARCHIVE_TOOL = 'bloomreach.flows.prepare_archive';
export const BLOOMREACH_GEO_ANALYSES_LIST_TOOL = 'bloomreach.geo_analyses.list';
export const BLOOMREACH_GEO_ANALYSES_VIEW_RESULTS_TOOL = 'bloomreach.geo_analyses.view_results';
export const BLOOMREACH_GEO_ANALYSES_PREPARE_CREATE_TOOL = 'bloomreach.geo_analyses.prepare_create';
export const BLOOMREACH_GEO_ANALYSES_PREPARE_CLONE_TOOL = 'bloomreach.geo_analyses.prepare_clone';
export const BLOOMREACH_GEO_ANALYSES_PREPARE_ARCHIVE_TOOL =
  'bloomreach.geo_analyses.prepare_archive';
export const BLOOMREACH_CUSTOMERS_LIST_TOOL = 'bloomreach.customers.list';
export const BLOOMREACH_CUSTOMERS_SEARCH_TOOL = 'bloomreach.customers.search';
export const BLOOMREACH_CUSTOMERS_VIEW_TOOL = 'bloomreach.customers.view';
export const BLOOMREACH_CUSTOMERS_PREPARE_CREATE_TOOL = 'bloomreach.customers.prepare_create';
export const BLOOMREACH_CUSTOMERS_PREPARE_UPDATE_TOOL = 'bloomreach.customers.prepare_update';
export const BLOOMREACH_CUSTOMERS_PREPARE_DELETE_TOOL = 'bloomreach.customers.prepare_delete';
export const BLOOMREACH_VOUCHERS_LIST_TOOL = 'bloomreach.vouchers.list';
export const BLOOMREACH_VOUCHERS_VIEW_STATUS_TOOL = 'bloomreach.vouchers.view_status';
export const BLOOMREACH_VOUCHERS_PREPARE_CREATE_TOOL = 'bloomreach.vouchers.prepare_create';
export const BLOOMREACH_VOUCHERS_PREPARE_ADD_TOOL = 'bloomreach.vouchers.prepare_add';
export const BLOOMREACH_VOUCHERS_PREPARE_DELETE_TOOL = 'bloomreach.vouchers.prepare_delete';
export const BLOOMREACH_ASSETS_EMAIL_TEMPLATES_LIST_TOOL = 'bloomreach.assets.email_templates.list';
export const BLOOMREACH_ASSETS_EMAIL_TEMPLATES_PREPARE_CREATE_TOOL =
  'bloomreach.assets.email_templates.prepare_create';
export const BLOOMREACH_ASSETS_WEBLAYER_TEMPLATES_LIST_TOOL =
  'bloomreach.assets.weblayer_templates.list';
export const BLOOMREACH_ASSETS_WEBLAYER_TEMPLATES_PREPARE_CREATE_TOOL =
  'bloomreach.assets.weblayer_templates.prepare_create';
export const BLOOMREACH_ASSETS_BLOCKS_LIST_TOOL = 'bloomreach.assets.blocks.list';
export const BLOOMREACH_ASSETS_BLOCKS_PREPARE_CREATE_TOOL =
  'bloomreach.assets.blocks.prepare_create';
export const BLOOMREACH_ASSETS_CUSTOM_ROWS_LIST_TOOL = 'bloomreach.assets.custom_rows.list';
export const BLOOMREACH_ASSETS_CUSTOM_ROWS_PREPARE_CREATE_TOOL =
  'bloomreach.assets.custom_rows.prepare_create';
export const BLOOMREACH_ASSETS_SNIPPETS_LIST_TOOL = 'bloomreach.assets.snippets.list';
export const BLOOMREACH_ASSETS_SNIPPETS_PREPARE_CREATE_TOOL =
  'bloomreach.assets.snippets.prepare_create';
export const BLOOMREACH_ASSETS_SNIPPETS_PREPARE_EDIT_TOOL =
  'bloomreach.assets.snippets.prepare_edit';
export const BLOOMREACH_ASSETS_FILES_LIST_TOOL = 'bloomreach.assets.files.list';
export const BLOOMREACH_ASSETS_FILES_PREPARE_UPLOAD_TOOL = 'bloomreach.assets.files.prepare_upload';
export const BLOOMREACH_ASSETS_FILES_PREPARE_DELETE_TOOL = 'bloomreach.assets.files.prepare_delete';
export const BLOOMREACH_ASSETS_PREPARE_CLONE_TOOL = 'bloomreach.assets.prepare_clone';
export const BLOOMREACH_ASSETS_PREPARE_ARCHIVE_TOOL = 'bloomreach.assets.prepare_archive';
export const BLOOMREACH_TAG_MANAGER_LIST_TOOL = 'bloomreach.tag_manager.list';
export const BLOOMREACH_TAG_MANAGER_VIEW_TOOL = 'bloomreach.tag_manager.view';
export const BLOOMREACH_TAG_MANAGER_PREPARE_CREATE_TOOL = 'bloomreach.tag_manager.prepare_create';
export const BLOOMREACH_TAG_MANAGER_PREPARE_ENABLE_TOOL = 'bloomreach.tag_manager.prepare_enable';
export const BLOOMREACH_TAG_MANAGER_PREPARE_DISABLE_TOOL = 'bloomreach.tag_manager.prepare_disable';
export const BLOOMREACH_TAG_MANAGER_PREPARE_EDIT_TOOL = 'bloomreach.tag_manager.prepare_edit';
export const BLOOMREACH_TAG_MANAGER_PREPARE_DELETE_TOOL = 'bloomreach.tag_manager.prepare_delete';
export const BLOOMREACH_METRICS_LIST_TOOL = 'bloomreach.metrics.list';
export const BLOOMREACH_METRICS_PREPARE_CREATE_TOOL = 'bloomreach.metrics.prepare_create';
export const BLOOMREACH_METRICS_PREPARE_EDIT_TOOL = 'bloomreach.metrics.prepare_edit';
export const BLOOMREACH_METRICS_PREPARE_DELETE_TOOL = 'bloomreach.metrics.prepare_delete';
export const BLOOMREACH_DATA_MANAGER_LIST_PROPERTIES_TOOL =
  'bloomreach.data_manager.list_properties';
export const BLOOMREACH_DATA_MANAGER_PREPARE_ADD_PROPERTY_TOOL =
  'bloomreach.data_manager.prepare_add_property';
export const BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_PROPERTY_TOOL =
  'bloomreach.data_manager.prepare_edit_property';
export const BLOOMREACH_DATA_MANAGER_LIST_EVENTS_TOOL = 'bloomreach.data_manager.list_events';
export const BLOOMREACH_DATA_MANAGER_PREPARE_ADD_EVENT_TOOL =
  'bloomreach.data_manager.prepare_add_event';
export const BLOOMREACH_DATA_MANAGER_LIST_DEFINITIONS_TOOL =
  'bloomreach.data_manager.list_definitions';
export const BLOOMREACH_DATA_MANAGER_PREPARE_ADD_DEFINITION_TOOL =
  'bloomreach.data_manager.prepare_add_definition';
export const BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_DEFINITION_TOOL =
  'bloomreach.data_manager.prepare_edit_definition';
export const BLOOMREACH_DATA_MANAGER_LIST_MAPPINGS_TOOL = 'bloomreach.data_manager.list_mappings';
export const BLOOMREACH_DATA_MANAGER_PREPARE_CONFIGURE_MAPPING_TOOL =
  'bloomreach.data_manager.prepare_configure_mapping';
export const BLOOMREACH_DATA_MANAGER_LIST_CONTENT_SOURCES_TOOL =
  'bloomreach.data_manager.list_content_sources';
export const BLOOMREACH_DATA_MANAGER_PREPARE_ADD_CONTENT_SOURCE_TOOL =
  'bloomreach.data_manager.prepare_add_content_source';
export const BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_CONTENT_SOURCE_TOOL =
  'bloomreach.data_manager.prepare_edit_content_source';
export const BLOOMREACH_DATA_MANAGER_PREPARE_SAVE_CHANGES_TOOL =
  'bloomreach.data_manager.prepare_save_changes';
export const BLOOMREACH_EXPORTS_LIST_TOOL = 'bloomreach.exports.list';
export const BLOOMREACH_EXPORTS_STATUS_TOOL = 'bloomreach.exports.status';
export const BLOOMREACH_EXPORTS_HISTORY_TOOL = 'bloomreach.exports.history';
export const BLOOMREACH_EXPORTS_PREPARE_CREATE_TOOL = 'bloomreach.exports.prepare_create';
export const BLOOMREACH_EXPORTS_PREPARE_RUN_TOOL = 'bloomreach.exports.prepare_run';
export const BLOOMREACH_EXPORTS_PREPARE_SCHEDULE_TOOL = 'bloomreach.exports.prepare_schedule';
export const BLOOMREACH_EXPORTS_PREPARE_DELETE_TOOL = 'bloomreach.exports.prepare_delete';
export const BLOOMREACH_INTEGRATIONS_LIST_TOOL = 'bloomreach.integrations.list';
export const BLOOMREACH_INTEGRATIONS_VIEW_TOOL = 'bloomreach.integrations.view';
export const BLOOMREACH_INTEGRATIONS_PREPARE_CREATE_TOOL = 'bloomreach.integrations.prepare_create';
export const BLOOMREACH_INTEGRATIONS_PREPARE_CONFIGURE_TOOL =
  'bloomreach.integrations.prepare_configure';
export const BLOOMREACH_INTEGRATIONS_PREPARE_ENABLE_TOOL = 'bloomreach.integrations.prepare_enable';
export const BLOOMREACH_INTEGRATIONS_PREPARE_DISABLE_TOOL =
  'bloomreach.integrations.prepare_disable';
export const BLOOMREACH_INTEGRATIONS_PREPARE_DELETE_TOOL = 'bloomreach.integrations.prepare_delete';
export const BLOOMREACH_INTEGRATIONS_PREPARE_TEST_TOOL = 'bloomreach.integrations.prepare_test';
export const BLOOMREACH_INITIATIVES_LIST_TOOL = 'bloomreach.initiatives.list';
export const BLOOMREACH_INITIATIVES_FILTER_TOOL = 'bloomreach.initiatives.filter';
export const BLOOMREACH_INITIATIVES_VIEW_TOOL = 'bloomreach.initiatives.view';
export const BLOOMREACH_INITIATIVES_PREPARE_CREATE_TOOL = 'bloomreach.initiatives.prepare_create';
export const BLOOMREACH_INITIATIVES_PREPARE_IMPORT_TOOL = 'bloomreach.initiatives.prepare_import';
export const BLOOMREACH_INITIATIVES_PREPARE_ADD_ITEMS_TOOL =
  'bloomreach.initiatives.prepare_add_items';
export const BLOOMREACH_INITIATIVES_PREPARE_ARCHIVE_TOOL = 'bloomreach.initiatives.prepare_archive';
export const BLOOMREACH_PROJECT_SETTINGS_VIEW_TOOL = 'bloomreach.project_settings.view';
export const BLOOMREACH_PROJECT_SETTINGS_TOKEN_TOOL = 'bloomreach.project_settings.token';
export const BLOOMREACH_PROJECT_SETTINGS_TERMS_TOOL = 'bloomreach.project_settings.terms';
export const BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_NAME_TOOL =
  'bloomreach.project_settings.prepare_update_name';
export const BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_URL_TOOL =
  'bloomreach.project_settings.prepare_update_url';
export const BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_TERMS_TOOL =
  'bloomreach.project_settings.prepare_update_terms';
export const BLOOMREACH_PROJECT_SETTINGS_TAGS_LIST_TOOL = 'bloomreach.project_settings.tags.list';
export const BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_CREATE_TOOL =
  'bloomreach.project_settings.tags.prepare_create';
export const BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_UPDATE_TOOL =
  'bloomreach.project_settings.tags.prepare_update';
export const BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_DELETE_TOOL =
  'bloomreach.project_settings.tags.prepare_delete';
export const BLOOMREACH_PROJECT_SETTINGS_VARIABLES_LIST_TOOL =
  'bloomreach.project_settings.variables.list';
export const BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_CREATE_TOOL =
  'bloomreach.project_settings.variables.prepare_create';
export const BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_UPDATE_TOOL =
  'bloomreach.project_settings.variables.prepare_update';
export const BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_DELETE_TOOL =
  'bloomreach.project_settings.variables.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_DEFAULTS_TOOL = 'bloomreach.campaign_settings.defaults';
export const BLOOMREACH_CAMPAIGN_SETTINGS_PREPARE_UPDATE_DEFAULTS_TOOL =
  'bloomreach.campaign_settings.prepare_update_defaults';
export const BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_LIST_TOOL =
  'bloomreach.campaign_settings.timezones.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.timezones.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.timezones.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.timezones.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_LIST_TOOL =
  'bloomreach.campaign_settings.languages.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.languages.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.languages.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.languages.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_LIST_TOOL =
  'bloomreach.campaign_settings.fonts.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.fonts.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.fonts.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.fonts.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_LIST_TOOL =
  'bloomreach.campaign_settings.throughput.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.throughput.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.throughput.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.throughput.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_LIST_TOOL =
  'bloomreach.campaign_settings.frequency.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.frequency.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.frequency.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.frequency.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_LIST_TOOL =
  'bloomreach.campaign_settings.consents.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.consents.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.consents.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.consents.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_LIST_TOOL =
  'bloomreach.campaign_settings.url_lists.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.url_lists.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.url_lists.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.url_lists.prepare_delete';
export const BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_LIST_TOOL =
  'bloomreach.campaign_settings.page_variables.list';
export const BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_CREATE_TOOL =
  'bloomreach.campaign_settings.page_variables.prepare_create';
export const BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_UPDATE_TOOL =
  'bloomreach.campaign_settings.page_variables.prepare_update';
export const BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_DELETE_TOOL =
  'bloomreach.campaign_settings.page_variables.prepare_delete';
export const BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_LIST_TOOL =
  'bloomreach.security_settings.ssh_tunnels.list';
export const BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_VIEW_TOOL =
  'bloomreach.security_settings.ssh_tunnels.view';
export const BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_PREPARE_CREATE_TOOL =
  'bloomreach.security_settings.ssh_tunnels.prepare_create';
export const BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_PREPARE_DELETE_TOOL =
  'bloomreach.security_settings.ssh_tunnels.prepare_delete';
export const BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_VIEW_TOOL =
  'bloomreach.security_settings.two_step.view';
export const BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_PREPARE_ENABLE_TOOL =
  'bloomreach.security_settings.two_step.prepare_enable';
export const BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_PREPARE_DISABLE_TOOL =
  'bloomreach.security_settings.two_step.prepare_disable';
export const BLOOMREACH_EVALUATION_SETTINGS_REVENUE_ATTRIBUTION_VIEW_TOOL =
  'bloomreach.evaluation_settings.revenue_attribution.view';
export const BLOOMREACH_EVALUATION_SETTINGS_REVENUE_ATTRIBUTION_PREPARE_CONFIGURE_TOOL =
  'bloomreach.evaluation_settings.revenue_attribution.prepare_configure';
export const BLOOMREACH_EVALUATION_SETTINGS_CURRENCY_VIEW_TOOL =
  'bloomreach.evaluation_settings.currency.view';
export const BLOOMREACH_EVALUATION_SETTINGS_CURRENCY_PREPARE_SET_TOOL =
  'bloomreach.evaluation_settings.currency.prepare_set';
export const BLOOMREACH_EVALUATION_SETTINGS_DASHBOARDS_VIEW_TOOL =
  'bloomreach.evaluation_settings.dashboards.view';
export const BLOOMREACH_EVALUATION_SETTINGS_DASHBOARDS_PREPARE_CONFIGURE_TOOL =
  'bloomreach.evaluation_settings.dashboards.prepare_configure';
export const BLOOMREACH_EVALUATION_SETTINGS_VOUCHER_MAPPING_VIEW_TOOL =
  'bloomreach.evaluation_settings.voucher_mapping.view';
export const BLOOMREACH_EVALUATION_SETTINGS_VOUCHER_MAPPING_PREPARE_CONFIGURE_TOOL =
  'bloomreach.evaluation_settings.voucher_mapping.prepare_configure';
export const BLOOMREACH_WEBLAYERS_LIST_TOOL = 'bloomreach.weblayers.list';
export const BLOOMREACH_WEBLAYERS_VIEW_PERFORMANCE_TOOL = 'bloomreach.weblayers.view_performance';
export const BLOOMREACH_WEBLAYERS_PREPARE_CREATE_TOOL = 'bloomreach.weblayers.prepare_create';
export const BLOOMREACH_WEBLAYERS_PREPARE_START_TOOL = 'bloomreach.weblayers.prepare_start';
export const BLOOMREACH_WEBLAYERS_PREPARE_STOP_TOOL = 'bloomreach.weblayers.prepare_stop';
export const BLOOMREACH_WEBLAYERS_PREPARE_CLONE_TOOL = 'bloomreach.weblayers.prepare_clone';
export const BLOOMREACH_WEBLAYERS_PREPARE_ARCHIVE_TOOL = 'bloomreach.weblayers.prepare_archive';
export const BLOOMREACH_REPORTS_LIST_TOOL = 'bloomreach.reports.list';
export const BLOOMREACH_REPORTS_VIEW_RESULTS_TOOL = 'bloomreach.reports.view_results';
export const BLOOMREACH_REPORTS_PREPARE_CREATE_TOOL = 'bloomreach.reports.prepare_create';
export const BLOOMREACH_REPORTS_PREPARE_EXPORT_TOOL = 'bloomreach.reports.prepare_export';
export const BLOOMREACH_REPORTS_PREPARE_CLONE_TOOL = 'bloomreach.reports.prepare_clone';
export const BLOOMREACH_REPORTS_PREPARE_ARCHIVE_TOOL = 'bloomreach.reports.prepare_archive';
export const BLOOMREACH_SEGMENTATIONS_LIST_TOOL = 'bloomreach.segmentations.list';
export const BLOOMREACH_SEGMENTATIONS_VIEW_SIZE_TOOL = 'bloomreach.segmentations.view_size';
export const BLOOMREACH_SEGMENTATIONS_VIEW_CUSTOMERS_TOOL =
  'bloomreach.segmentations.view_customers';
export const BLOOMREACH_SEGMENTATIONS_PREPARE_CREATE_TOOL =
  'bloomreach.segmentations.prepare_create';
export const BLOOMREACH_SEGMENTATIONS_PREPARE_CLONE_TOOL = 'bloomreach.segmentations.prepare_clone';
export const BLOOMREACH_SEGMENTATIONS_PREPARE_ARCHIVE_TOOL =
  'bloomreach.segmentations.prepare_archive';
export const BLOOMREACH_SQL_REPORTS_LIST_TOOL = 'bloomreach.sql_reports.list';
export const BLOOMREACH_SQL_REPORTS_VIEW_TOOL = 'bloomreach.sql_reports.view';
export const BLOOMREACH_SQL_REPORTS_PREPARE_CREATE_TOOL = 'bloomreach.sql_reports.prepare_create';
export const BLOOMREACH_SQL_REPORTS_PREPARE_EXECUTE_TOOL = 'bloomreach.sql_reports.prepare_execute';
export const BLOOMREACH_SQL_REPORTS_PREPARE_EXPORT_RESULTS_TOOL =
  'bloomreach.sql_reports.prepare_export_results';
export const BLOOMREACH_SQL_REPORTS_PREPARE_CLONE_TOOL = 'bloomreach.sql_reports.prepare_clone';
export const BLOOMREACH_SQL_REPORTS_PREPARE_ARCHIVE_TOOL = 'bloomreach.sql_reports.prepare_archive';
export const BLOOMREACH_CATALOGS_LIST_TOOL = 'bloomreach.catalogs.list';
export const BLOOMREACH_CATALOGS_VIEW_ITEMS_TOOL = 'bloomreach.catalogs.view_items';
export const BLOOMREACH_CATALOGS_PREPARE_CREATE_TOOL = 'bloomreach.catalogs.prepare_create';
export const BLOOMREACH_CATALOGS_PREPARE_ADD_ITEMS_TOOL = 'bloomreach.catalogs.prepare_add_items';
export const BLOOMREACH_CATALOGS_PREPARE_UPDATE_ITEMS_TOOL =
  'bloomreach.catalogs.prepare_update_items';
export const BLOOMREACH_CATALOGS_PREPARE_DELETE_TOOL = 'bloomreach.catalogs.prepare_delete';
export const BLOOMREACH_IMPORTS_LIST_TOOL = 'bloomreach.imports.list';
export const BLOOMREACH_IMPORTS_VIEW_STATUS_TOOL = 'bloomreach.imports.view_status';
export const BLOOMREACH_IMPORTS_PREPARE_CREATE_TOOL = 'bloomreach.imports.prepare_create';
export const BLOOMREACH_IMPORTS_PREPARE_SCHEDULE_TOOL = 'bloomreach.imports.prepare_schedule';
export const BLOOMREACH_IMPORTS_PREPARE_CANCEL_TOOL = 'bloomreach.imports.prepare_cancel';
export const BLOOMREACH_USE_CASES_LIST_TOOL = 'bloomreach.use_cases.list';
export const BLOOMREACH_USE_CASES_SEARCH_TOOL = 'bloomreach.use_cases.search';
export const BLOOMREACH_USE_CASES_VIEW_TOOL = 'bloomreach.use_cases.view';
export const BLOOMREACH_USE_CASES_PROJECT_LIST_TOOL = 'bloomreach.use_cases.project_list';
export const BLOOMREACH_USE_CASES_PREPARE_DEPLOY_TOOL = 'bloomreach.use_cases.prepare_deploy';
export const BLOOMREACH_USE_CASES_PREPARE_FAVORITE_TOOL = 'bloomreach.use_cases.prepare_favorite';
export const BLOOMREACH_USE_CASES_PREPARE_UNFAVORITE_TOOL =
  'bloomreach.use_cases.prepare_unfavorite';
export const BLOOMREACH_ACCESS_LIST_MEMBERS_TOOL = 'bloomreach.access.list_members';
export const BLOOMREACH_ACCESS_PREPARE_INVITE_TOOL = 'bloomreach.access.prepare_invite';
export const BLOOMREACH_ACCESS_PREPARE_UPDATE_ROLE_TOOL = 'bloomreach.access.prepare_update_role';
export const BLOOMREACH_ACCESS_PREPARE_REMOVE_MEMBER_TOOL =
  'bloomreach.access.prepare_remove_member';
export const BLOOMREACH_ACCESS_LIST_API_KEYS_TOOL = 'bloomreach.access.list_api_keys';
export const BLOOMREACH_ACCESS_PREPARE_CREATE_API_KEY_TOOL =
  'bloomreach.access.prepare_create_api_key';
export const BLOOMREACH_ACCESS_PREPARE_DELETE_API_KEY_TOOL =
  'bloomreach.access.prepare_delete_api_key';

export const BLOOMREACH_MCP_TOOL_NAMES = [
  BLOOMREACH_STATUS_TOOL,
  BLOOMREACH_DASHBOARDS_LIST_TOOL,
  BLOOMREACH_DASHBOARDS_PREPARE_CREATE_TOOL,
  BLOOMREACH_DASHBOARDS_PREPARE_SET_HOME_TOOL,
  BLOOMREACH_DASHBOARDS_PREPARE_DELETE_TOOL,
  BLOOMREACH_PERFORMANCE_PROJECT_TOOL,
  BLOOMREACH_PERFORMANCE_CHANNEL_TOOL,
  BLOOMREACH_PERFORMANCE_USAGE_TOOL,
  BLOOMREACH_PERFORMANCE_OVERVIEW_TOOL,
  BLOOMREACH_PERFORMANCE_HEALTH_TOOL,
  BLOOMREACH_SCENARIOS_LIST_TOOL,
  BLOOMREACH_SCENARIOS_VIEW_TOOL,
  BLOOMREACH_SCENARIOS_PREPARE_CREATE_TOOL,
  BLOOMREACH_SCENARIOS_PREPARE_START_TOOL,
  BLOOMREACH_SCENARIOS_PREPARE_STOP_TOOL,
  BLOOMREACH_SCENARIOS_PREPARE_CLONE_TOOL,
  BLOOMREACH_SCENARIOS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_LIST_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_VIEW_RESULTS_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_CREATE_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_SEND_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_CLONE_TOOL,
  BLOOMREACH_EMAIL_CAMPAIGNS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_SURVEYS_LIST_TOOL,
  BLOOMREACH_SURVEYS_VIEW_RESULTS_TOOL,
  BLOOMREACH_SURVEYS_PREPARE_CREATE_TOOL,
  BLOOMREACH_SURVEYS_PREPARE_START_TOOL,
  BLOOMREACH_SURVEYS_PREPARE_STOP_TOOL,
  BLOOMREACH_SURVEYS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_CAMPAIGNS_CALENDAR_VIEW_TOOL,
  BLOOMREACH_CAMPAIGNS_CALENDAR_FILTER_TOOL,
  BLOOMREACH_CAMPAIGNS_CALENDAR_PREPARE_EXPORT_TOOL,
  BLOOMREACH_TRENDS_LIST_TOOL,
  BLOOMREACH_TRENDS_VIEW_RESULTS_TOOL,
  BLOOMREACH_TRENDS_PREPARE_CREATE_TOOL,
  BLOOMREACH_TRENDS_PREPARE_CLONE_TOOL,
  BLOOMREACH_TRENDS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_FUNNELS_LIST_TOOL,
  BLOOMREACH_FUNNELS_VIEW_RESULTS_TOOL,
  BLOOMREACH_FUNNELS_PREPARE_CREATE_TOOL,
  BLOOMREACH_FUNNELS_PREPARE_CLONE_TOOL,
  BLOOMREACH_FUNNELS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_RETENTIONS_LIST_TOOL,
  BLOOMREACH_RETENTIONS_VIEW_RESULTS_TOOL,
  BLOOMREACH_RETENTIONS_PREPARE_CREATE_TOOL,
  BLOOMREACH_RETENTIONS_PREPARE_CLONE_TOOL,
  BLOOMREACH_RETENTIONS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_FLOWS_LIST_TOOL,
  BLOOMREACH_FLOWS_VIEW_RESULTS_TOOL,
  BLOOMREACH_FLOWS_PREPARE_CREATE_TOOL,
  BLOOMREACH_FLOWS_PREPARE_CLONE_TOOL,
  BLOOMREACH_FLOWS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_GEO_ANALYSES_LIST_TOOL,
  BLOOMREACH_GEO_ANALYSES_VIEW_RESULTS_TOOL,
  BLOOMREACH_GEO_ANALYSES_PREPARE_CREATE_TOOL,
  BLOOMREACH_GEO_ANALYSES_PREPARE_CLONE_TOOL,
  BLOOMREACH_GEO_ANALYSES_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_CUSTOMERS_LIST_TOOL,
  BLOOMREACH_CUSTOMERS_SEARCH_TOOL,
  BLOOMREACH_CUSTOMERS_VIEW_TOOL,
  BLOOMREACH_CUSTOMERS_PREPARE_CREATE_TOOL,
  BLOOMREACH_CUSTOMERS_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CUSTOMERS_PREPARE_DELETE_TOOL,
  BLOOMREACH_VOUCHERS_LIST_TOOL,
  BLOOMREACH_VOUCHERS_VIEW_STATUS_TOOL,
  BLOOMREACH_VOUCHERS_PREPARE_CREATE_TOOL,
  BLOOMREACH_VOUCHERS_PREPARE_ADD_TOOL,
  BLOOMREACH_VOUCHERS_PREPARE_DELETE_TOOL,
  BLOOMREACH_ASSETS_EMAIL_TEMPLATES_LIST_TOOL,
  BLOOMREACH_ASSETS_EMAIL_TEMPLATES_PREPARE_CREATE_TOOL,
  BLOOMREACH_ASSETS_WEBLAYER_TEMPLATES_LIST_TOOL,
  BLOOMREACH_ASSETS_WEBLAYER_TEMPLATES_PREPARE_CREATE_TOOL,
  BLOOMREACH_ASSETS_BLOCKS_LIST_TOOL,
  BLOOMREACH_ASSETS_BLOCKS_PREPARE_CREATE_TOOL,
  BLOOMREACH_ASSETS_CUSTOM_ROWS_LIST_TOOL,
  BLOOMREACH_ASSETS_CUSTOM_ROWS_PREPARE_CREATE_TOOL,
  BLOOMREACH_ASSETS_SNIPPETS_LIST_TOOL,
  BLOOMREACH_ASSETS_SNIPPETS_PREPARE_CREATE_TOOL,
  BLOOMREACH_ASSETS_SNIPPETS_PREPARE_EDIT_TOOL,
  BLOOMREACH_ASSETS_FILES_LIST_TOOL,
  BLOOMREACH_ASSETS_FILES_PREPARE_UPLOAD_TOOL,
  BLOOMREACH_ASSETS_FILES_PREPARE_DELETE_TOOL,
  BLOOMREACH_ASSETS_PREPARE_CLONE_TOOL,
  BLOOMREACH_ASSETS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_TAG_MANAGER_LIST_TOOL,
  BLOOMREACH_TAG_MANAGER_VIEW_TOOL,
  BLOOMREACH_TAG_MANAGER_PREPARE_CREATE_TOOL,
  BLOOMREACH_TAG_MANAGER_PREPARE_ENABLE_TOOL,
  BLOOMREACH_TAG_MANAGER_PREPARE_DISABLE_TOOL,
  BLOOMREACH_TAG_MANAGER_PREPARE_EDIT_TOOL,
  BLOOMREACH_TAG_MANAGER_PREPARE_DELETE_TOOL,
  BLOOMREACH_METRICS_LIST_TOOL,
  BLOOMREACH_METRICS_PREPARE_CREATE_TOOL,
  BLOOMREACH_METRICS_PREPARE_EDIT_TOOL,
  BLOOMREACH_METRICS_PREPARE_DELETE_TOOL,
  BLOOMREACH_DATA_MANAGER_LIST_PROPERTIES_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_ADD_PROPERTY_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_PROPERTY_TOOL,
  BLOOMREACH_DATA_MANAGER_LIST_EVENTS_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_ADD_EVENT_TOOL,
  BLOOMREACH_DATA_MANAGER_LIST_DEFINITIONS_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_ADD_DEFINITION_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_DEFINITION_TOOL,
  BLOOMREACH_DATA_MANAGER_LIST_MAPPINGS_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_CONFIGURE_MAPPING_TOOL,
  BLOOMREACH_DATA_MANAGER_LIST_CONTENT_SOURCES_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_ADD_CONTENT_SOURCE_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_EDIT_CONTENT_SOURCE_TOOL,
  BLOOMREACH_DATA_MANAGER_PREPARE_SAVE_CHANGES_TOOL,
  BLOOMREACH_EXPORTS_LIST_TOOL,
  BLOOMREACH_EXPORTS_STATUS_TOOL,
  BLOOMREACH_EXPORTS_HISTORY_TOOL,
  BLOOMREACH_EXPORTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_EXPORTS_PREPARE_RUN_TOOL,
  BLOOMREACH_EXPORTS_PREPARE_SCHEDULE_TOOL,
  BLOOMREACH_EXPORTS_PREPARE_DELETE_TOOL,
  BLOOMREACH_INTEGRATIONS_LIST_TOOL,
  BLOOMREACH_INTEGRATIONS_VIEW_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_CREATE_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_CONFIGURE_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_ENABLE_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_DISABLE_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_DELETE_TOOL,
  BLOOMREACH_INTEGRATIONS_PREPARE_TEST_TOOL,
  BLOOMREACH_INITIATIVES_LIST_TOOL,
  BLOOMREACH_INITIATIVES_FILTER_TOOL,
  BLOOMREACH_INITIATIVES_VIEW_TOOL,
  BLOOMREACH_INITIATIVES_PREPARE_CREATE_TOOL,
  BLOOMREACH_INITIATIVES_PREPARE_IMPORT_TOOL,
  BLOOMREACH_INITIATIVES_PREPARE_ADD_ITEMS_TOOL,
  BLOOMREACH_INITIATIVES_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_VIEW_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TOKEN_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TERMS_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_NAME_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_URL_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_PREPARE_UPDATE_TERMS_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TAGS_LIST_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_CREATE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_UPDATE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_TAGS_PREPARE_DELETE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_VARIABLES_LIST_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_CREATE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_UPDATE_TOOL,
  BLOOMREACH_PROJECT_SETTINGS_VARIABLES_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_DEFAULTS_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_PREPARE_UPDATE_DEFAULTS_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_TIMEZONES_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_LANGUAGES_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FONTS_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_THROUGHPUT_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_FREQUENCY_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_CONSENTS_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_URL_LISTS_PREPARE_DELETE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_LIST_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_CREATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_UPDATE_TOOL,
  BLOOMREACH_CAMPAIGN_SETTINGS_PAGE_VARIABLES_PREPARE_DELETE_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_LIST_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_VIEW_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_PREPARE_CREATE_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_SSH_TUNNELS_PREPARE_DELETE_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_VIEW_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_PREPARE_ENABLE_TOOL,
  BLOOMREACH_SECURITY_SETTINGS_TWO_STEP_PREPARE_DISABLE_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_REVENUE_ATTRIBUTION_VIEW_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_REVENUE_ATTRIBUTION_PREPARE_CONFIGURE_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_CURRENCY_VIEW_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_CURRENCY_PREPARE_SET_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_DASHBOARDS_VIEW_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_DASHBOARDS_PREPARE_CONFIGURE_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_VOUCHER_MAPPING_VIEW_TOOL,
  BLOOMREACH_EVALUATION_SETTINGS_VOUCHER_MAPPING_PREPARE_CONFIGURE_TOOL,
  BLOOMREACH_WEBLAYERS_LIST_TOOL,
  BLOOMREACH_WEBLAYERS_VIEW_PERFORMANCE_TOOL,
  BLOOMREACH_WEBLAYERS_PREPARE_CREATE_TOOL,
  BLOOMREACH_WEBLAYERS_PREPARE_START_TOOL,
  BLOOMREACH_WEBLAYERS_PREPARE_STOP_TOOL,
  BLOOMREACH_WEBLAYERS_PREPARE_CLONE_TOOL,
  BLOOMREACH_WEBLAYERS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_REPORTS_LIST_TOOL,
  BLOOMREACH_REPORTS_VIEW_RESULTS_TOOL,
  BLOOMREACH_REPORTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_REPORTS_PREPARE_EXPORT_TOOL,
  BLOOMREACH_REPORTS_PREPARE_CLONE_TOOL,
  BLOOMREACH_REPORTS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_SEGMENTATIONS_LIST_TOOL,
  BLOOMREACH_SEGMENTATIONS_VIEW_SIZE_TOOL,
  BLOOMREACH_SEGMENTATIONS_VIEW_CUSTOMERS_TOOL,
  BLOOMREACH_SEGMENTATIONS_PREPARE_CREATE_TOOL,
  BLOOMREACH_SEGMENTATIONS_PREPARE_CLONE_TOOL,
  BLOOMREACH_SEGMENTATIONS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_SQL_REPORTS_LIST_TOOL,
  BLOOMREACH_SQL_REPORTS_VIEW_TOOL,
  BLOOMREACH_SQL_REPORTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_SQL_REPORTS_PREPARE_EXECUTE_TOOL,
  BLOOMREACH_SQL_REPORTS_PREPARE_EXPORT_RESULTS_TOOL,
  BLOOMREACH_SQL_REPORTS_PREPARE_CLONE_TOOL,
  BLOOMREACH_SQL_REPORTS_PREPARE_ARCHIVE_TOOL,
  BLOOMREACH_CATALOGS_LIST_TOOL,
  BLOOMREACH_CATALOGS_VIEW_ITEMS_TOOL,
  BLOOMREACH_CATALOGS_PREPARE_CREATE_TOOL,
  BLOOMREACH_CATALOGS_PREPARE_ADD_ITEMS_TOOL,
  BLOOMREACH_CATALOGS_PREPARE_UPDATE_ITEMS_TOOL,
  BLOOMREACH_CATALOGS_PREPARE_DELETE_TOOL,
  BLOOMREACH_IMPORTS_LIST_TOOL,
  BLOOMREACH_IMPORTS_VIEW_STATUS_TOOL,
  BLOOMREACH_IMPORTS_PREPARE_CREATE_TOOL,
  BLOOMREACH_IMPORTS_PREPARE_SCHEDULE_TOOL,
  BLOOMREACH_IMPORTS_PREPARE_CANCEL_TOOL,
  BLOOMREACH_USE_CASES_LIST_TOOL,
  BLOOMREACH_USE_CASES_SEARCH_TOOL,
  BLOOMREACH_USE_CASES_VIEW_TOOL,
  BLOOMREACH_USE_CASES_PROJECT_LIST_TOOL,
  BLOOMREACH_USE_CASES_PREPARE_DEPLOY_TOOL,
  BLOOMREACH_USE_CASES_PREPARE_FAVORITE_TOOL,
  BLOOMREACH_USE_CASES_PREPARE_UNFAVORITE_TOOL,
  BLOOMREACH_ACCESS_LIST_MEMBERS_TOOL,
  BLOOMREACH_ACCESS_PREPARE_INVITE_TOOL,
  BLOOMREACH_ACCESS_PREPARE_UPDATE_ROLE_TOOL,
  BLOOMREACH_ACCESS_PREPARE_REMOVE_MEMBER_TOOL,
  BLOOMREACH_ACCESS_LIST_API_KEYS_TOOL,
  BLOOMREACH_ACCESS_PREPARE_CREATE_API_KEY_TOOL,
  BLOOMREACH_ACCESS_PREPARE_DELETE_API_KEY_TOOL,
] as const;

export type BloomreachMcpToolName = (typeof BLOOMREACH_MCP_TOOL_NAMES)[number];
